/**
 * http://qt.gtimg.cn/q=sz000858
 */
class StockPriceTX {
  String key = ''; //0-未知，可能是在腾讯数据库中的主键
  String name = ''; //1-名字
  String code = ''; //2-代码
  double price = 0; //3-当前价格
  double yesterdayClose = 0; //4-昨日收盘价
  double open = 0; //5-今日开盘价
  int transactionCount = 0; //6-成交量（手）
  int buy = 0; //7-外盘
  int sell = 0; //8-内盘
  int buyCount1 = 0; //9-买一(手)
  double buyPrice1 = 0; //10-“买一”报价
  int buyCount2 = 0; //11-买二
  double buyPrice2 = 0; //12-买二
  int buyCount3 = 0; //13-买三
  double buyPrice3 = 0; //14-买三
  int buyCount4 = 0; //15-买四
  double buyPrice4 = 0; //16-买四
  int buyCount5 = 0; //17-买五
  double buyPrice5 = 0; //18-买五
  int sellCount1 = 0; //19-卖一(手)
  double sellPrice1 = 0; //20-“卖一”报价
  int sellCount2 = 0; //21-卖二
  double sellPrice2 = 0; //22-卖二
  int sellCount3 = 0; //23-卖三
  double sellPrice3 = 0; //24-卖三
  int sellCount4 = 0; //25-卖四
  double sellPrice4 = 0; //26-卖四
  int sellCount5 = 0; //27-卖五
  double sellPrice5 = 0; //28-卖五
  int deal = 0; //29-最近逐笔成交
  String time = ''; //30-时间
  double rise_v = 0; //31-涨跌
  double rise_p = 0; //32-涨跌百分比%
  double high = 0; //33-今日最高价
  double low = 0; //34-今日最低价
  String price_count_amount = ''; //35-价格/成交量（手）/成交额
  int transactionCount2 = 0; //36-成交量（手）
  double transactionAmount = 0; //37-成交额（万）
  double change = 0; //38-换手率
  double shiyinglv = 0; //39-市盈率
  double high2 = 0; //41-最高
  double low2 = 0; //42-最低
  double zhenfu = 0; //43-振幅
  double shizhi_lt = 0; //44-流通市值
  double shizhi_z = 0; //45-总市值
  double shijinglv = 0; //46-市净率
  double zt = 0; //47-涨停价
  double dt = 0; //48-跌停价
  void loadData(List<String> data) {
    if (data.isNotEmpty && data.length >= 49) {
      key = data[0]; //0-未知，可能是在腾讯数据库中的主键
      name = data[1]; //1-名字
      code = data[2]; //2-代码
      price = double.parse(data[3]); //3-当前价格
      yesterdayClose = double.parse(data[4]); //4-昨日收盘价
      open = double.parse(data[5]); //5-今日开盘价
      transactionCount = int.parse(data[6]); //6-成交量（手）
      buy = int.parse(data[7]); //7-外盘
      sell = int.parse(data[8]); //8-内盘
      buyCount1 = int.parse(data[9]); //9-买一(手)
      buyPrice1 = double.parse(data[10]); //10-“买一”报价
      buyCount2 = int.parse(data[11]); //11-买二
      buyPrice2 = double.parse(data[12]); //12-买二
      buyCount3 = int.parse(data[13]); //13-买三
      buyPrice3 = double.parse(data[14]); //14-买三
      buyCount4 = int.parse(data[15]); //15-买四
      buyPrice4 = double.parse(data[16]); //16-买四
      buyCount5 = int.parse(data[17]); //17-买五
      buyPrice5 = double.parse(data[18]); //18-买五
      sellCount1 = int.parse(data[19]); //19-卖一(手)
      sellPrice1 = double.parse(data[20]); //20-“卖一”报价
      sellCount2 = int.parse(data[21]); //21-卖二
      sellPrice2 = double.parse(data[22]); //22-卖二
      sellCount3 = int.parse(data[23]); //23-卖三
      sellPrice3 = double.parse(data[24]); //24-卖三
      sellCount4 = int.parse(data[25]); //25-卖四
      sellPrice4 = double.parse(data[26]); //26-卖四
      sellCount5 = int.parse(data[27]); //27-卖五
      sellPrice5 = double.parse(data[28]); //28-卖五
      deal = int.parse(data[29]); //29-最近逐笔成交
      time = data[30]; //30-时间
      rise_v = double.parse(data[31]); //31-涨跌
      rise_p = double.parse(data[32]); //32-涨跌百分比%
      high = double.parse(data[33]); //33-今日最高价
      low = double.parse(data[34]); //34-今日最低价
      price_count_amount = data[35]; //35-价格/成交量（手）/成交额
      transactionCount2 = int.parse(data[36]); //36-成交量（手）
      transactionAmount = double.parse(data[37]); //37-成交额（万）
      change = double.parse(data[38]); //38-换手率
      shiyinglv = double.parse(data[39]); //39-市盈率
      high2 = double.parse(data[41]); //41-最高
      low2 = double.parse(data[42]); //42-最低
      zhenfu = double.parse(data[43]); //43-振幅
      shizhi_lt = double.parse(data[44]); //44-流通市值
      shizhi_z = double.parse(data[45]); //45-总市值
      shijinglv = double.parse(data[46]); //46-市净率
      zt = double.parse(data[47]); //47-涨停价
      dt = double.parse(data[48]); //48-跌停价
    }
  }
}
